"""
main.py — FastAPI application entry point.

Start the server:
  uvicorn main:app --reload --port 8000

Interactive API docs (auto-generated by FastAPI):
  http://localhost:8000/docs       ← Swagger UI
  http://localhost:8000/redoc      ← ReDoc
"""

from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session

# Internal imports
from database import engine, get_db
import models
import schemas

# Import all 5 routers
from routers import onboard, xp, roundups, rewards, habits

# ---------------------------------------------------------------------------
# 1. Create all database tables
# ---------------------------------------------------------------------------
# This runs once at startup. If scotia.db already exists and tables are
# already created, create_all() is a safe no-op — it won't drop or alter
# existing tables. Run seed.py separately after this to populate demo data.
models.Base.metadata.create_all(bind=engine)

# ---------------------------------------------------------------------------
# 2. Create the FastAPI app instance
# ---------------------------------------------------------------------------
app = FastAPI(
    title="Instant Starter Portfolio API",
    description=(
        "Scotiabank Hackathon backend — gamified micro-investing for new account holders. "
        "Features: XP system, daily habits, spare-change roundups, and rewards marketplace."
    ),
    version="1.0.0",
)

# ---------------------------------------------------------------------------
# 3. CORS Middleware
# ---------------------------------------------------------------------------
# During development we allow all origins so the React / mobile frontend
# can call the API from any port (e.g. localhost:3000, localhost:19000).
# In production, replace ["*"] with the actual frontend domain.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],        # tighten this for production
    allow_credentials=True,
    allow_methods=["*"],        # GET, POST, PUT, DELETE, OPTIONS
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# 4. Register routers
# ---------------------------------------------------------------------------
# Each router already has its own prefix (e.g. "/onboard", "/xp") defined
# in its own file — we just mount them here.
app.include_router(onboard.router)
app.include_router(xp.router)
app.include_router(roundups.router)
app.include_router(rewards.router)
app.include_router(habits.router)

# ---------------------------------------------------------------------------
# 5. Root health-check endpoint
# ---------------------------------------------------------------------------
@app.get("/", tags=["Health"])
def root():
    """
    Health check — confirms the API is running.
    Used by deployment platforms (Railway, Render, etc.) to verify liveness.
    """
    return {
        "status": "ok",
        "app": "Instant Starter Portfolio API",
        "version": "1.0.0",
        "docs": "/docs",
    }


# ---------------------------------------------------------------------------
# 6. User endpoints
# ---------------------------------------------------------------------------
@app.post("/user", response_model=schemas.UserOut, tags=["User"], status_code=201)
def create_user(body: schemas.UserCreate, db: Session = Depends(get_db)):
    """
    Create a new user account.
    Called by the frontend on the very first onboarding screen (name + email).
    After this, the frontend uses the returned user.id for all subsequent calls.

    Returns 409 if the email is already registered — prevents duplicates.
    Also auto-creates an empty Portfolio and a Streak record so every other
    endpoint can assume these rows exist without defensive checks.
    """
    # --- Guard: email must be unique ---
    existing = db.query(models.User).filter(models.User.email == body.email).first()
    if existing:
        raise HTTPException(
            status_code=409,
            detail=f"An account with email '{body.email}' already exists.",
        )

    # --- Create the user ---
    user = models.User(name=body.name, email=body.email)
    db.add(user)
    db.flush()   # get user.id before creating linked records

    # --- Auto-create an empty portfolio ---
    # Every user needs a portfolio from day one so deposit/roundup endpoints
    # never have to handle the "no portfolio yet" case.
    portfolio = models.Portfolio(
        user_id=user.id,
        balance=0.0,
        total_invested=0.0,
        market_value=0.0,
    )
    db.add(portfolio)

    # --- Auto-create a streak record starting at 0 ---
    streak = models.Streak(
        user_id=user.id,
        current_streak=0,
        longest_streak=0,
    )
    db.add(streak)

    db.commit()
    db.refresh(user)
    return user


@app.get("/user/{user_id}", response_model=schemas.UserOut, tags=["User"])
def get_user(user_id: int, db: Session = Depends(get_db)):
    """
    Fetch a user's profile by ID.
    Used by the frontend header/nav to display the user's name and goal.
    Also useful for debugging — confirm the seeded user exists at /user/1.
    """
    user = db.query(models.User).filter(models.User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return user

@app.get("/users", response_model=list[schemas.UserOut], tags=["User"])
def get_users(db: Session = Depends(get_db)):
    """
    Fetch all users.
    Used for admin purposes or to display a list of users.
    """
    return db.query(models.User).all()
