"""
main.py — FastAPI application entry point.

Start the server:
  uvicorn main:app --reload --port 8000

Interactive API docs (auto-generated by FastAPI):
  http://localhost:8000/docs       ← Swagger UI
  http://localhost:8000/redoc      ← ReDoc
"""

from datetime import datetime

from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import func, inspect, text
from sqlalchemy.orm import Session

# Internal imports
from database import engine, get_db, SessionLocal
import models
import schemas

# Import all 5 routers
from routers import onboard, xp, roundups, rewards, habits, goals
from routers.xp import get_total_xp

# ---------------------------------------------------------------------------
# 1. Create all database tables
# ---------------------------------------------------------------------------
# This runs once at startup. If scotia.db already exists and tables are
# already created, create_all() is a safe no-op — it won't drop or alter
# existing tables. Run seed.py separately after this to populate demo data.
models.Base.metadata.create_all(bind=engine)


def _ensure_user_goal_target_amount_column() -> None:
    inspector = inspect(engine)
    columns = {column["name"] for column in inspector.get_columns("users")}
    if "goal_target_amount" not in columns:
        with engine.begin() as connection:
            connection.execute(text("ALTER TABLE users ADD COLUMN goal_target_amount FLOAT"))


def _latest_goal_for_user(db: Session, user_id: int) -> models.InvestmentGoal | None:
    return db.query(models.InvestmentGoal).filter(models.InvestmentGoal.user_id == user_id).order_by(
        models.InvestmentGoal.created_at.desc(),
        models.InvestmentGoal.id.desc(),
    ).first()


def _ensure_investment_goals_schema() -> None:
    inspector = inspect(engine)
    if not inspector.has_table("investment_goals"):
        return

    unique_constraints = inspector.get_unique_constraints("investment_goals")
    needs_rebuild = any("user_id" in constraint.get("column_names", []) for constraint in unique_constraints)
    if not needs_rebuild:
        return

    with engine.begin() as connection:
        connection.execute(text("ALTER TABLE investment_goals RENAME TO investment_goals_legacy"))
        models.InvestmentGoal.__table__.create(bind=connection, checkfirst=True)
        connection.execute(text(
            "INSERT INTO investment_goals (id, user_id, goal, target_amount, created_at, updated_at) "
            "SELECT id, user_id, goal, target_amount, created_at, updated_at FROM investment_goals_legacy"
        ))
        connection.execute(text("DROP TABLE investment_goals_legacy"))


def _sync_legacy_goals() -> None:
    db = SessionLocal()
    try:
        users = db.query(models.User).all()
        for user in users:
            goal_row = _latest_goal_for_user(db, user.id)
            if goal_row is None and user.goal:
                goal_row = models.InvestmentGoal(
                    user_id=user.id,
                    goal=user.goal,
                    target_amount=user.goal_target_amount,
                )
                db.add(goal_row)
            elif goal_row is not None:
                user.goal = goal_row.goal
                user.goal_target_amount = goal_row.target_amount
        db.commit()
    finally:
        db.close()


_ensure_user_goal_target_amount_column()
_ensure_investment_goals_schema()
_sync_legacy_goals()

# ---------------------------------------------------------------------------
# 2. Create the FastAPI app instance
# ---------------------------------------------------------------------------
app = FastAPI(
    title="Instant Starter Portfolio API",
    description=(
        "Scotiabank Hackathon backend — gamified micro-investing for new account holders. "
        "Features: XP system, daily habits, spare-change roundups, and rewards marketplace."
    ),
    version="1.0.0",
)

# ---------------------------------------------------------------------------
# 3. CORS Middleware
# ---------------------------------------------------------------------------
# During development we allow all origins so the React / mobile frontend
# can call the API from any port (e.g. localhost:3000, localhost:19000).
# In production, replace ["*"] with the actual frontend domain.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],        # tighten this for production
    allow_credentials=False,
    allow_methods=["*"],        # GET, POST, PUT, DELETE, OPTIONS
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# 4. Register routers
# ---------------------------------------------------------------------------
# Each router already has its own prefix (e.g. "/onboard", "/xp") defined
# in its own file — we just mount them here.
app.include_router(onboard.router)
app.include_router(xp.router)
app.include_router(roundups.router)
app.include_router(rewards.router)
app.include_router(habits.router)
app.include_router(goals.router)

# ---------------------------------------------------------------------------
# 5. Root health-check endpoint
# ---------------------------------------------------------------------------
@app.get("/", tags=["Health"])
def root():
    """
    Health check — confirms the API is running.
    Used by deployment platforms (Railway, Render, etc.) to verify liveness.
    """
    return {
        "status": "ok",
        "app": "Instant Starter Portfolio API",
        "version": "1.0.0",
        "docs": "/docs",
    }


# ---------------------------------------------------------------------------
# 6. User endpoints
# ---------------------------------------------------------------------------
@app.post("/user", response_model=schemas.UserOut, tags=["User"], status_code=201)
def create_user(body: schemas.UserCreate, db: Session = Depends(get_db)):
    """
    Create a new user account.
    Called by the frontend on the very first onboarding screen (name + email).
    After this, the frontend uses the returned user.id for all subsequent calls.

    Returns 409 if the email is already registered — prevents duplicates.
    Also auto-creates an empty Portfolio and a Streak record so every other
    endpoint can assume these rows exist without defensive checks.
    """
    # --- Guard: email must be unique ---
    existing = db.query(models.User).filter(models.User.email == body.email).first()
    if existing:
        raise HTTPException(
            status_code=409,
            detail=f"An account with email '{body.email}' already exists.",
        )

    # --- Create the user ---
    user = models.User(name=body.name, email=body.email)
    db.add(user)
    db.flush()   # get user.id before creating linked records

    # --- Auto-create an empty portfolio ---
    # Every user needs a portfolio from day one so deposit/roundup endpoints
    # never have to handle the "no portfolio yet" case.
    portfolio = models.Portfolio(
        user_id=user.id,
        balance=0.0,
        total_invested=0.0,
        market_value=0.0,
    )
    db.add(portfolio)

    # --- Auto-create a streak record starting at 0 ---
    streak = models.Streak(
        user_id=user.id,
        current_streak=0,
        longest_streak=0,
    )
    db.add(streak)

    db.commit()
    db.refresh(user)
    return user


@app.get("/user/{user_id}", response_model=schemas.UserOut, tags=["User"])
def get_user(user_id: int, db: Session = Depends(get_db)):
    """
    Fetch a user's profile by ID.
    Used by the frontend header/nav to display the user's name and goal.
    Also useful for debugging — confirm the seeded user exists at /user/1.
    """
    user = db.query(models.User).filter(models.User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    goal_row = _latest_goal_for_user(db, user_id)
    if goal_row:
        user.goal = goal_row.goal
        user.goal_target_amount = goal_row.target_amount
    return user

@app.get("/users", response_model=list[schemas.UserOut], tags=["User"])
def get_users(db: Session = Depends(get_db)):
    """
    Fetch all users.
    Used for admin purposes or to display a list of users.
    """
    users = db.query(models.User).all()
    for user in users:
        goal_row = _latest_goal_for_user(db, user.id)
        if goal_row:
            user.goal = goal_row.goal
            user.goal_target_amount = goal_row.target_amount
    return users


@app.get("/dashboard/{user_id}", response_model=schemas.DashboardOut, tags=["Dashboard"])
def get_dashboard(user_id: int, db: Session = Depends(get_db)):
    """
    Return a single aggregated payload for the frontend.
    This is the bridge between the static screens and the live backend data.
    """
    user = db.query(models.User).filter(models.User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    goal_row = _latest_goal_for_user(db, user_id)
    if goal_row:
        user.goal = goal_row.goal
        user.goal_target_amount = goal_row.target_amount

    portfolio = db.query(models.Portfolio).filter(models.Portfolio.user_id == user_id).first()
    if not portfolio:
        raise HTTPException(status_code=404, detail="Portfolio not found")

    streak = db.query(models.Streak).filter(models.Streak.user_id == user_id).first()
    if not streak:
        streak = models.Streak(user_id=user_id, current_streak=0, longest_streak=0)

    total_xp = get_total_xp(user_id, db)
    level = total_xp // 100

    active_rewards = db.query(models.Reward).filter(models.Reward.is_active == True).count()
    habits_total = db.query(models.Habit).filter(models.Habit.is_active == True).count()

    habits_today_completed = db.query(models.HabitCompletion).filter(
        models.HabitCompletion.user_id == user_id,
        models.HabitCompletion.completed_at >= datetime.utcnow().replace(
            hour=0, minute=0, second=0, microsecond=0
        ),
    ).count()

    roundup_total = db.query(func.sum(models.Transaction.amount)).join(models.Portfolio).filter(
        models.Portfolio.user_id == user_id,
        models.Transaction.type == "roundup",
    ).scalar()

    if user.kyc_verified:
        kyc_status = "Verified"
    else:
        kyc_status = "Not Started"

    return schemas.DashboardOut(
        user_id=user.id,
        name=user.name,
        goal=user.goal,
        goal_target_amount=user.goal_target_amount,
        kyc_verified=user.kyc_verified,
        kyc_status=kyc_status,
        balance=round(portfolio.balance or 0.0, 2),
        total_invested=round(portfolio.total_invested or 0.0, 2),
        market_value=round(portfolio.market_value or 0.0, 2),
        total_xp=total_xp,
        level=level,
        current_streak=streak.current_streak if streak else 0,
        longest_streak=streak.longest_streak if streak else 0,
        active_rewards=active_rewards,
        habits_today_completed=habits_today_completed,
        habits_total=habits_total,
        roundup_total=round(float(roundup_total), 2) if roundup_total else 0.0,
        updated_at=portfolio.updated_at,
    )
